config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  root to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, except: [:index, :destroy] do
    put :become_candidate
  end

  resources :elections, only: [:index, :show]

  resources :votes, only: [:index, :create]

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :elections, only: [:new, :create, :destroy, :edit, :update]
  end

  namespace :candidates do
    post '/:user_id/elections/:id', to: 'elections#update'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true
  enum role: [:user, :candidate, :admin]

  has_many :ballots, as: :candidate
  has_many :elections, through: :ballots, as: :candidate

  has_many :votes, as: :recipient
  has_many :elections, through: :votes, as: :recipient

  has_many :votes, as: :voter
  has_many :elections, through: :votes, as: :voter

  def full_name
    "#{first_name} #{last_name}"
  end

  def has_voted?(election)
    votes.pluck(:election_id).include?(election.id)
  end

  def voted_for(election)
    votes.where(election_id:election.id).first.recipient.full_name
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  include ApplicationHelper
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "#{full_name(@user)} was successfully deleted."
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create]
  before_action :set_user, with: [:edit, :update, :become_candidate]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account created!"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      render :edit
    end
  end

  def become_candidate
    if @user.user?
      @user.candidate!
      flash[:success] = "You have been made into a candidate.  Now you can run in elections."
      redirect_to @user
    else
      flash[:error] = "Only Users Can Become Candidates"
      redirect_to @user
    end
  end

  private

   def user_params
     params.require(:user).permit(:first_name, :last_name, :email, :password, :profile)
   end

   def set_user
     @user = current_user
   end
end

app/views/users/_form.html.haml
= form_for @user do |f|
  = render partial: "shared/errors", locals: { target: @user }
  = render partial: "users/role_partials/edit/#{@user.role}", locals: {:f=> f}
  = f.submit

app/views/users/edit.html.haml
%h1 Edit Your Profile

= render partial: "form"

app/views/users/new.html.haml
.container.bg-white.page-container
  %h1 Create your Account

  = render partial: "form"

app/views/users/show.html.haml
.container.bg-white.page-container
  %h1 Your Profile
  - if current_user.user?
    %p= link_to "Become a Candidate", user_become_candidate_path(current_user), method: :put

  = render partial: "users/role_partials/show/#{current_user.role}"

  %p= link_to "Edit Your Profile", edit_user_path(current_user)