config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  root to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, except: [:index, :destroy] do
    put :become_candidate
  end

  resources :elections, only: [:index, :show]

  resources :votes, only: [:index, :create]

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :elections, only: [:new, :create, :destroy, :edit, :update]
  end

  namespace :candidates do
    post '/:user_id/elections/:id', to: 'elections#update'
  end
end

app/views/shared/_errors.html.haml
- if target.errors.any?
  .alert.alert-danger
    %h2= "#{pluralize(target.errors.count, "error")} prohibited this record from being saved:"
    %ul
      - target.errors.full_messages.each do |error|
        %li= error

app/views/shared/_nav.html.haml
%nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse
  %button{class:"navbar-toggler navbar-toggler-right",
          type:"button",
          data: {"toggle":"collapse",
                 "target":"#navbarNav"},
          aria: {"controls":"navbarNav",
                 "expanded":"false",
                 "label":"Toggle navigation"}}
    %span.navbar-toggler-icon
  = link_to root_path, {class: "navbar-brand"} do
    %span.glyphicon.glyphicon-briefcase
    Voting Bloc
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      - if current_user
        %li.nav-item= link_to"Upcoming Votes", elections_path, {class: "nav-link"}
        %li.nav-item= link_to "Your Profile", user_path(current_user), {class: "nav-link"}
    .user-logged-in.my-2.my-lg-0
      - if current_user
        = "Welcome, #{full_name(current_user)}!"
        = link_to "Logout", logout_path, method: :delete
      - else
        = link_to "New Account", new_user_path