config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  root to: 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, except: [:index, :destroy] do
    put :become_candidate
  end

  resources :elections, only: [:index, :show]

  resources :votes, only: [:index, :create]

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :elections, only: [:new, :create, :destroy, :edit, :update]
  end

  namespace :candidates do
    post '/:user_id/elections/:id', to: 'elections#update'
  end
end

app/models/election.rb
class Election < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :topic, presence: true

  has_many :ballots
  has_many :candidates, through: :ballots, source: :candidate, source_type: "User"

  has_many :votes
  has_many :recipients, through: :votes, source: :recipient, source_type: "User"
  has_many :voters, through: :votes, source: :voter, source_type: "User"

  def started?
    start_date <= Date.today
  end

  def ended?
    end_date <= Date.today
  end

  def can_run? (user)
    user.candidate? && !candidates.include?(user) && !started? && !ended?
  end

  def can_be_deleted?(user)
    not_started_and_admin?(user)
  end

  def can_be_edited?(user)
    not_started_and_admin?(user)
  end

  def vote_status(user)
    return "not_started" unless started?
    return "closed" if ended?
    return "result" if user.has_voted?(self)
    "vote"
  end

  def winner_with_votes
    results.take(1)[0]
  end

  def results
    votes.joins('INNER JOIN users on users.id = votes.recipient_id')
                                .group("(users.first_name || ' ' || users.last_name)")
                                .order('count_all DESC').count
  end

  def self.upcoming_elections
    Election.where('start_date > ?', Date.today)
  end

  def self.past_elections
    Election.where('end_date < ?', Date.today)
  end

  def self.active_elections
    Election.where('start_date < ? AND end_date > ?', Date.today, Date.today)
  end

  private

   def not_started_and_admin?(user)
     !started? && user.admin?
   end
end

app/controllers/admin/elections_controller.rb
class Admin::ElectionsController < Admin::BaseController
  before_action :get_election, only: [:destroy, :edit, :update]
  before_action :get_candidates, only: [:new, :edit]

  def new
    @election = Election.new
  end

  def create
    @election = Election.create(election_params)
    if @election.save
      flash[:success] = "Election created!"
      redirect_to elections_path
    else
      render :new
    end
  end

  def destroy
    @election.destroy
    flash[:success] = "Election '#{@election.topic}' Deleted!"
    redirect_to elections_path
  end

  def edit
  end

  def update
    @election.update(election_params)
    if @election.save
      flash[:success] = "Election Updated!"
      redirect_to @election
    else
      render :edit
    end
  end

  private

   def election_params
     params[:election][:start_date] = Date.strptime(params[:election][:start_date],'%Y-%m-%d')
     params[:election][:end_date] = Date.strptime(params[:election][:end_date],'%Y-%m-%d')
     params.require(:election).permit(:start_date, :end_date, :topic, :description, candidate_ids:[])
   end

   def get_election
     @election = Election.find(params[:id])
   end

   def get_candidates
     @candidates = User.candidate
   end
end

app/controllers/candidates/elections_controller.rb
class Candidates::ElectionsController < Candidates::BaseController
  def update
    election = Election.find(params[:id])
    candidate = User.find(params[:user_id])
    election.candidates << candidate
    flash[:success] = "You are now running in this election!"
    redirect_to election
  end
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :require_user

  def index
    if params[:elections] == "upcoming"
      @title = "Upcoming Elections"
      @elections = Election.upcoming_elections
    elsif params[:elections] == "past"
      @title = "Past Elections"
      @elections = Election.past_elections
    else
      @title = "Active Elections"
      @elections = Election.active_elections
    end
  end

  def show
    @election = Election.find(params[:id])
    @vote = Vote.new
  end
end

app/views/elections/_all_results.html.haml
%h3 All Results:
- if election.results.empty?
  %p No votes for this election
- else
  = react_component "Results", results: render(partial:'elections/results.json', locals: {election: election.results})
  -# = react_component "Results", results: @election.results
  -# - @election.results.each do |result|
  -#   %p #{result[0]}: #{result[1]}

app/views/elections/index.html.haml
.container.bg-white.page-container
  %h1 Active Elections
  - if current_user.admin?
    %p= link_to "New Election", new_admin_election_path
  %p= link_to "Active Elections", elections_path
  %p= link_to "Upcoming Elections", elections_path(elections: 'upcoming')
  %p= link_to "Past Elections", elections_path(elections: 'past')


  %table.table.table-striped
    %thead
      %tr.thead-inverse
        %th Topic
        %th Start Date
        %th End Date
        %th
        %th
        %th
    %tbody
      - @elections.each do |election|
        %tr
          %td= election.topic
          %td= election.start_date
          %td= election.end_date
          %td= link_to "View", election, {class: "btn btn-secondary btn-view"}
          %td
            - if election.can_be_edited?(current_user)
              = link_to "Edit", edit_admin_election_path(election), {class: "btn btn-primary btn-edit"}
          %td
            - if election.can_be_deleted?(current_user)
              = link_to "Delete", admin_election_path(election), {method: :delete, class: "btn btn-danger btn-delete"}

app/views/elections/show.html.haml
.container.bg-white.page-container
  %h1= @election.topic

  %p= @election.description

  %h2 Candidates
  - if @election.can_run?(current_user)
    %p= link_to "Run in this Election", {controller: "candidates/elections", action: "update", user_id: current_user.id}, {method: :post}
  %ul.list-group
    - @election.candidates.each do |candidate|
      %li.list-group-item
        = full_name(candidate)

  - if @election.can_be_edited?(current_user)
    %p= link_to "Edit", edit_admin_election_path(@election), {class: "btn btn-primary btn-edit"}
  - if @election.can_be_deleted?(current_user)
    %p= link_to "Delete", admin_election_path(@election), {method: :delete, class: "btn btn-danger btn-delete"}

  %h2 Voting
  #voting
    = render "elections/vote_status/#{@election.vote_status(current_user)}", election: @election
  -# = react_component 'Voting', { user: current_user,
  -#                               vote_status: @election.vote_status(current_user),
  -#                               election: @election,
  -#                               results: @election.results,
  -#                               candidates: @election.candidates
  -#                             }
  %p= link_to "Active Elections", elections_path